export const rows = [
    {
        id: '1',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        type: 'Holiday',
        reason: 'Christmas with my chinese family',
        start: new Date('2022-02-07').toLocaleDateString('en-GB'),
        end: new Date('2022-02-09').toLocaleDateString('en-GB'),
        status: 'waiting',
    },
    {
        id: '2',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        type: 'Holiday',
        reason: 'Christmas with my chinese family',
        start: new Date('2022-02-07').toLocaleDateString('en-GB'),
        end: new Date('2022-02-09').toLocaleDateString('en-GB'),
        status: 'waiting',
    },
    {
        id: '3',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        type: 'Holiday',
        reason: 'Christmas with my chinese family',
        start: new Date('2022-02-07').toLocaleDateString('en-GB'),
        end: new Date('2022-02-09').toLocaleDateString('en-GB'),
        status: 'waiting',
    },
    {
        id: '4',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        type: 'Holiday',
        reason: 'Christmas with my chinese family',
        start: new Date('2022-02-07').toLocaleDateString('en-GB'),
        end: new Date('2022-02-09').toLocaleDateString('en-GB'),
        status: 'waiting',
    }, {
        id: '5',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        type: 'Holiday',
        reason: 'Christmas with my chinese family',
        start: new Date('2022-02-07').toLocaleDateString('en-GB'),
        end: new Date('2022-02-09').toLocaleDateString('en-GB'),
        status: 'waiting',
    },
    {
        id: '6',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        type: 'Holiday',
        reason: 'Christmas with my chinese family',
        start: new Date('2022-02-07').toLocaleDateString('en-GB'),
        end: new Date('2022-02-09').toLocaleDateString('en-GB'),
        status: 'waiting',
    }, {
        id: '7',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        type: 'Holiday',
        reason: 'Christmas with my chinese family',
        start: new Date('2022-02-07').toLocaleDateString('en-GB'),
        end: new Date('2022-02-09').toLocaleDateString('en-GB'),
        status: 'waiting',
    },
    {
        id: '8',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        type: 'Holiday',
        reason: 'Christmas with my chinese family',
        start: new Date('2022-02-07').toLocaleDateString('en-GB'),
        end: new Date('2022-02-09').toLocaleDateString('en-GB'),
        status: 'waiting',
    }, {
        id: '9',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        type: 'Holiday',
        reason: 'Christmas with my chinese family',
        start: new Date('2022-02-07').toLocaleDateString('en-GB'),
        end: new Date('2022-02-09').toLocaleDateString('en-GB'),
        status: 'waiting',
    },
    {
        id: '10',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        type: 'Holiday',
        reason: 'Christmas with my chinese family',
        start: new Date('2022-02-07').toLocaleDateString('en-GB'),
        end: new Date('2022-02-09').toLocaleDateString('en-GB'),
        status: 'waiting',
    },
]