export const rows = [
    {
        id: '1',
        head: 'Free Antigen Test Kit!',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        content: 'Free Antigen Test Kit!',
        status: 'waiting',
    },
    {
        id: '2',
        head: 'Free Antigen Test Kit!',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        content: 'Free Antigen Test Kit!',
        status: 'waiting',
    },
    {
        id: '3',
        head: 'Free Antigen Test Kit!',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        content: 'Free Antigen Test Kit!',
        status: 'waiting',
    },
    {
        id: '4',
        head: 'Free Antigen Test Kit!',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        content: 'Free Antigen Test Kit!',
        status: 'waiting',
    }, {
        id: '5',
        head: 'Free Antigen Test Kit!',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        content: 'Free Antigen Test Kit!',
        status: 'waiting',
    },
    {
        id: '6',
        head: 'Free Antigen Test Kit!',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        content: 'Free Antigen Test Kit!',
        status: 'waiting',
    }, {
        id: '7',
        head: 'Free Antigen Test Kit!',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        content: 'Free Antigen Test Kit!',
        status: 'waiting',
    },
    {
        id: '8',
        head: 'Free Antigen Test Kit!',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        content: 'Free Antigen Test Kit!',
        status: 'waiting',
    }, {
        id: '9',
        head: 'Free Antigen Test Kit!',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        content: 'Free Antigen Test Kit!',
        status: 'waiting',
    },
    {
        id: '10',
        head: 'Free Antigen Test Kit!',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        content: 'Free Antigen Test Kit!',
        status: 'waiting',
    },
]