export const rows = [
    {
        id: '1',
        type: 'Salary certification',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        purpose: 'request salary certificate for credit card application process',
        status: 'waiting',
    },
    {
        id: '2',
        type: 'Employment certification',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        purpose: 'apply the new job',
        status: 'waiting',
    },
    {
        id: '3',
        type: 'leave booking record',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        purpose: 'check for available leave remain',
        status: 'waiting',
    },
    {
        id: '4',
        type: 'Salary certification',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        purpose: 'request salary certificate for credit card application process',
        status: 'waiting',
    }, {
        id: '5',
        type: 'Salary certification',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        purpose: 'request salary certificate for credit card application process',
        status: 'waiting',
    },
    {
        id: '6',
        type: 'Employment certification',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        purpose: 'transfer to another department',
        status: 'waiting',
    }, {
        id: '7',
        type: 'Employment certification',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        purpose: 'apply the new job',
        status: 'waiting',
    },
    {
        id: '8',
        type: 'Salary certification',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        purpose: 'request salary certificate for credit card application process',
        status: 'waiting',
    }, {
        id: '9',
        type: 'Salary certification',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        purpose: 'request salary certificate for credit card application process',
        status: 'waiting',
    },
    {
        id: '10',
        type: 'Salary certification',
        date: new Date('2022-02-05').toLocaleDateString('en-GB'),
        purpose: 'request salary certificate for credit card application process',
        status: 'waiting',
    },
]